import { MODELING_SLOT_KEYS } from "@/lib/site-media/site-media.registry";

import type { ModelingSlotCopyBundle, ModelingSlotCopyEntry } from "./modeling-slot-copy.types";

/**
 * Empty fallback used when DB rows are missing.
 * Product requirement: render only DB-managed text; no hardcoded copy in code.
 */
const EMPTY_MODELING_SLOT_COPY_ENTRY: ModelingSlotCopyEntry = {
  title: "",
  titleMobile: "",
  body: "",
  bodyMobile: "",
};

export const MODELING_SLOT_DEFAULT_COPY: ModelingSlotCopyBundle = {
  [MODELING_SLOT_KEYS.HIP_HOP]: { ...EMPTY_MODELING_SLOT_COPY_ENTRY },
  [MODELING_SLOT_KEYS.BRIDAL]: { ...EMPTY_MODELING_SLOT_COPY_ENTRY },
  [MODELING_SLOT_KEYS.PORTRAIT]: { ...EMPTY_MODELING_SLOT_COPY_ENTRY },
  [MODELING_SLOT_KEYS.MECHANICAL]: { ...EMPTY_MODELING_SLOT_COPY_ENTRY },
  [MODELING_SLOT_KEYS.HERITAGE]: { ...EMPTY_MODELING_SLOT_COPY_ENTRY },
  [MODELING_SLOT_KEYS.HIGH_JEWELRY]: { ...EMPTY_MODELING_SLOT_COPY_ENTRY },
};

export function defaultModelingSlotCopyBundle(): ModelingSlotCopyBundle {
  return {
    [MODELING_SLOT_KEYS.HIP_HOP]: { ...MODELING_SLOT_DEFAULT_COPY[MODELING_SLOT_KEYS.HIP_HOP] },
    [MODELING_SLOT_KEYS.BRIDAL]: { ...MODELING_SLOT_DEFAULT_COPY[MODELING_SLOT_KEYS.BRIDAL] },
    [MODELING_SLOT_KEYS.PORTRAIT]: { ...MODELING_SLOT_DEFAULT_COPY[MODELING_SLOT_KEYS.PORTRAIT] },
    [MODELING_SLOT_KEYS.MECHANICAL]: { ...MODELING_SLOT_DEFAULT_COPY[MODELING_SLOT_KEYS.MECHANICAL] },
    [MODELING_SLOT_KEYS.HERITAGE]: { ...MODELING_SLOT_DEFAULT_COPY[MODELING_SLOT_KEYS.HERITAGE] },
    [MODELING_SLOT_KEYS.HIGH_JEWELRY]: { ...MODELING_SLOT_DEFAULT_COPY[MODELING_SLOT_KEYS.HIGH_JEWELRY] },
  };
}
