import { LANDING_SECTION_IDS } from "@/constants";
import { toCopyLines } from "@/lib/modeling-specialization-copy/normalize-modeling-specialization-copy";
import type { LandingModelingMedia } from "@/lib/site-media/get-landing-site-media";
import { MODELING_SLOT_KEYS } from "@/lib/site-media/site-media.registry";
import {
  ModelingSpecializationTitle,
  ModelingBlockHipHop,
  ModelingBlockBridal,
  ModelingBlockHighJewelry,
  ModelingBlockMechanical,
  ModelingBlockPortrait,
  ModelingBlockHeritage,
} from "./modeling";

import "./modeling/modeling-cms-mobile-font.css";
import "./modeling/modeling-section-scale.css";

type SectionModelingProps = {
  modeling: LandingModelingMedia;
  isAndroidViewport: boolean;
};

/**
 * Modeling Specialization section. 2×3 grid — քարտերը լրիվ սյուն, aspect 83/43, փոքր gap, սուր անկյուններ.
 */
export function SectionModeling({
  modeling,
  isAndroidViewport,
}: SectionModelingProps) {
  return (
    <section
      id={LANDING_SECTION_IDS.SPECIALIZATIONS}
      className="bg-white px-3 md:px-5"
      aria-labelledby="modeling-specialization"
    >
      <div className="modeling-specialization-cq mx-auto w-full max-w-[1920px]">
        <div className="modeling-specialization-scale py-6 md:pt-[calc(var(--modeling-scale-padding-y-md)*var(--ms,1))] md:pb-[calc(var(--modeling-scale-padding-b-md)*var(--ms,1))]">
          <div className="flex min-h-[calc(140px*var(--ms,1))] w-full min-w-0 flex-col items-center justify-center overflow-visible py-6 md:min-h-[calc(200px*var(--ms,1))] md:justify-center md:overflow-hidden md:py-0">
            <ModelingSpecializationTitle />
          </div>

          <div className="modeling-specialization-card-text-scale grid min-w-0 grid-cols-1 justify-items-center gap-[calc(0.625rem*var(--ms,1))] sm:grid-cols-2 lg:gap-[calc(0.5rem*var(--ms,1))]">
          <ModelingBlockHipHop
            imageUrlDesktop={modeling[MODELING_SLOT_KEYS.HIP_HOP].desktop}
            imageUrlMobile={modeling[MODELING_SLOT_KEYS.HIP_HOP].mobile}
            imageUrlTablet={modeling[MODELING_SLOT_KEYS.HIP_HOP].tablet}
            titleDesktop={modeling[MODELING_SLOT_KEYS.HIP_HOP].titleDesktop}
            titleMobile={modeling[MODELING_SLOT_KEYS.HIP_HOP].titleMobile}
            titleTablet={modeling[MODELING_SLOT_KEYS.HIP_HOP].titleTablet}
            titleDesktopOffsetY={modeling[MODELING_SLOT_KEYS.HIP_HOP].titleDesktopOffsetY}
            titleDesktopOffsetX={modeling[MODELING_SLOT_KEYS.HIP_HOP].titleDesktopOffsetX}
            titleMobileOffsetY={modeling[MODELING_SLOT_KEYS.HIP_HOP].titleMobileOffsetY}
            titleMobileOffsetX={modeling[MODELING_SLOT_KEYS.HIP_HOP].titleMobileOffsetX}
            titleTabletOffsetY={modeling[MODELING_SLOT_KEYS.HIP_HOP].titleTabletOffsetY}
            titleTabletOffsetX={modeling[MODELING_SLOT_KEYS.HIP_HOP].titleTabletOffsetX}
            descriptionLinesDesktop={toCopyLines(
              modeling[MODELING_SLOT_KEYS.HIP_HOP].bodyDesktop,
            )}
            descriptionLinesMobile={toCopyLines(
              modeling[MODELING_SLOT_KEYS.HIP_HOP].bodyMobile,
            )}
            descriptionLinesTablet={toCopyLines(
              modeling[MODELING_SLOT_KEYS.HIP_HOP].bodyTablet,
            )}
            bodyDesktopOffsetY={modeling[MODELING_SLOT_KEYS.HIP_HOP].bodyDesktopOffsetY}
            bodyDesktopOffsetX={modeling[MODELING_SLOT_KEYS.HIP_HOP].bodyDesktopOffsetX}
            bodyMobileOffsetY={modeling[MODELING_SLOT_KEYS.HIP_HOP].bodyMobileOffsetY}
            bodyMobileOffsetX={modeling[MODELING_SLOT_KEYS.HIP_HOP].bodyMobileOffsetX}
            bodyTabletOffsetY={modeling[MODELING_SLOT_KEYS.HIP_HOP].bodyTabletOffsetY}
            bodyTabletOffsetX={modeling[MODELING_SLOT_KEYS.HIP_HOP].bodyTabletOffsetX}
            mobilePreviewTitleFontPx={
              modeling[MODELING_SLOT_KEYS.HIP_HOP].mobilePreviewTitleFontPx
            }
            mobilePreviewBodyFontPx={
              modeling[MODELING_SLOT_KEYS.HIP_HOP].mobilePreviewBodyFontPx
            }
          />
          <ModelingBlockBridal
            imageUrlDesktop={modeling[MODELING_SLOT_KEYS.BRIDAL].desktop}
            imageUrlMobile={modeling[MODELING_SLOT_KEYS.BRIDAL].mobile}
            imageUrlTablet={modeling[MODELING_SLOT_KEYS.BRIDAL].tablet}
            titleDesktop={modeling[MODELING_SLOT_KEYS.BRIDAL].titleDesktop}
            titleMobile={modeling[MODELING_SLOT_KEYS.BRIDAL].titleMobile}
            titleTablet={modeling[MODELING_SLOT_KEYS.BRIDAL].titleTablet}
            titleDesktopOffsetY={modeling[MODELING_SLOT_KEYS.BRIDAL].titleDesktopOffsetY}
            titleDesktopOffsetX={modeling[MODELING_SLOT_KEYS.BRIDAL].titleDesktopOffsetX}
            titleMobileOffsetY={modeling[MODELING_SLOT_KEYS.BRIDAL].titleMobileOffsetY}
            titleMobileOffsetX={modeling[MODELING_SLOT_KEYS.BRIDAL].titleMobileOffsetX}
            titleTabletOffsetY={modeling[MODELING_SLOT_KEYS.BRIDAL].titleTabletOffsetY}
            titleTabletOffsetX={modeling[MODELING_SLOT_KEYS.BRIDAL].titleTabletOffsetX}
            descriptionLinesDesktop={toCopyLines(
              modeling[MODELING_SLOT_KEYS.BRIDAL].bodyDesktop,
            )}
            descriptionLinesMobile={toCopyLines(
              modeling[MODELING_SLOT_KEYS.BRIDAL].bodyMobile,
            )}
            descriptionLinesTablet={toCopyLines(
              modeling[MODELING_SLOT_KEYS.BRIDAL].bodyTablet,
            )}
            bodyDesktopOffsetY={modeling[MODELING_SLOT_KEYS.BRIDAL].bodyDesktopOffsetY}
            bodyDesktopOffsetX={modeling[MODELING_SLOT_KEYS.BRIDAL].bodyDesktopOffsetX}
            bodyMobileOffsetY={modeling[MODELING_SLOT_KEYS.BRIDAL].bodyMobileOffsetY}
            bodyMobileOffsetX={modeling[MODELING_SLOT_KEYS.BRIDAL].bodyMobileOffsetX}
            bodyTabletOffsetY={modeling[MODELING_SLOT_KEYS.BRIDAL].bodyTabletOffsetY}
            bodyTabletOffsetX={modeling[MODELING_SLOT_KEYS.BRIDAL].bodyTabletOffsetX}
            mobilePreviewTitleFontPx={
              modeling[MODELING_SLOT_KEYS.BRIDAL].mobilePreviewTitleFontPx
            }
            mobilePreviewBodyFontPx={
              modeling[MODELING_SLOT_KEYS.BRIDAL].mobilePreviewBodyFontPx
            }
          />
          <ModelingBlockPortrait
            imageUrlDesktop={modeling[MODELING_SLOT_KEYS.PORTRAIT].desktop}
            imageUrlMobile={modeling[MODELING_SLOT_KEYS.PORTRAIT].mobile}
            imageUrlTablet={modeling[MODELING_SLOT_KEYS.PORTRAIT].tablet}
            tabletAssetPresent={modeling[MODELING_SLOT_KEYS.PORTRAIT].hasTabletR2Upload}
            titleDesktop={modeling[MODELING_SLOT_KEYS.PORTRAIT].titleDesktop}
            titleMobile={modeling[MODELING_SLOT_KEYS.PORTRAIT].titleMobile}
            titleTablet={modeling[MODELING_SLOT_KEYS.PORTRAIT].titleTablet}
            titleDesktopOffsetY={modeling[MODELING_SLOT_KEYS.PORTRAIT].titleDesktopOffsetY}
            titleDesktopOffsetX={modeling[MODELING_SLOT_KEYS.PORTRAIT].titleDesktopOffsetX}
            titleMobileOffsetY={modeling[MODELING_SLOT_KEYS.PORTRAIT].titleMobileOffsetY}
            titleMobileOffsetX={modeling[MODELING_SLOT_KEYS.PORTRAIT].titleMobileOffsetX}
            titleTabletOffsetY={modeling[MODELING_SLOT_KEYS.PORTRAIT].titleTabletOffsetY}
            titleTabletOffsetX={modeling[MODELING_SLOT_KEYS.PORTRAIT].titleTabletOffsetX}
            descriptionLinesDesktop={toCopyLines(
              modeling[MODELING_SLOT_KEYS.PORTRAIT].bodyDesktop,
            )}
            descriptionLinesMobile={toCopyLines(
              modeling[MODELING_SLOT_KEYS.PORTRAIT].bodyMobile,
            )}
            descriptionLinesTablet={toCopyLines(
              modeling[MODELING_SLOT_KEYS.PORTRAIT].bodyTablet,
            )}
            bodyDesktopOffsetY={modeling[MODELING_SLOT_KEYS.PORTRAIT].bodyDesktopOffsetY}
            bodyDesktopOffsetX={modeling[MODELING_SLOT_KEYS.PORTRAIT].bodyDesktopOffsetX}
            bodyMobileOffsetY={modeling[MODELING_SLOT_KEYS.PORTRAIT].bodyMobileOffsetY}
            bodyMobileOffsetX={modeling[MODELING_SLOT_KEYS.PORTRAIT].bodyMobileOffsetX}
            bodyTabletOffsetY={modeling[MODELING_SLOT_KEYS.PORTRAIT].bodyTabletOffsetY}
            bodyTabletOffsetX={modeling[MODELING_SLOT_KEYS.PORTRAIT].bodyTabletOffsetX}
            mobilePreviewTitleFontPx={
              modeling[MODELING_SLOT_KEYS.PORTRAIT].mobilePreviewTitleFontPx
            }
            mobilePreviewBodyFontPx={
              modeling[MODELING_SLOT_KEYS.PORTRAIT].mobilePreviewBodyFontPx
            }
          />
          <ModelingBlockMechanical
            imageUrlDesktop={modeling[MODELING_SLOT_KEYS.MECHANICAL].desktop}
            imageUrlMobile={modeling[MODELING_SLOT_KEYS.MECHANICAL].mobile}
            imageUrlTablet={modeling[MODELING_SLOT_KEYS.MECHANICAL].tablet}
            titleDesktop={modeling[MODELING_SLOT_KEYS.MECHANICAL].titleDesktop}
            titleMobile={modeling[MODELING_SLOT_KEYS.MECHANICAL].titleMobile}
            titleTablet={modeling[MODELING_SLOT_KEYS.MECHANICAL].titleTablet}
            titleDesktopOffsetY={modeling[MODELING_SLOT_KEYS.MECHANICAL].titleDesktopOffsetY}
            titleDesktopOffsetX={modeling[MODELING_SLOT_KEYS.MECHANICAL].titleDesktopOffsetX}
            titleMobileOffsetY={modeling[MODELING_SLOT_KEYS.MECHANICAL].titleMobileOffsetY}
            titleMobileOffsetX={modeling[MODELING_SLOT_KEYS.MECHANICAL].titleMobileOffsetX}
            titleTabletOffsetY={modeling[MODELING_SLOT_KEYS.MECHANICAL].titleTabletOffsetY}
            titleTabletOffsetX={modeling[MODELING_SLOT_KEYS.MECHANICAL].titleTabletOffsetX}
            descriptionLinesDesktop={toCopyLines(
              modeling[MODELING_SLOT_KEYS.MECHANICAL].bodyDesktop,
            )}
            descriptionLinesMobile={toCopyLines(
              modeling[MODELING_SLOT_KEYS.MECHANICAL].bodyMobile,
            )}
            descriptionLinesTablet={toCopyLines(
              modeling[MODELING_SLOT_KEYS.MECHANICAL].bodyTablet,
            )}
            bodyDesktopOffsetY={modeling[MODELING_SLOT_KEYS.MECHANICAL].bodyDesktopOffsetY}
            bodyDesktopOffsetX={modeling[MODELING_SLOT_KEYS.MECHANICAL].bodyDesktopOffsetX}
            bodyMobileOffsetY={modeling[MODELING_SLOT_KEYS.MECHANICAL].bodyMobileOffsetY}
            bodyMobileOffsetX={modeling[MODELING_SLOT_KEYS.MECHANICAL].bodyMobileOffsetX}
            bodyTabletOffsetY={modeling[MODELING_SLOT_KEYS.MECHANICAL].bodyTabletOffsetY}
            bodyTabletOffsetX={modeling[MODELING_SLOT_KEYS.MECHANICAL].bodyTabletOffsetX}
            isAndroidViewport={isAndroidViewport}
            mobilePreviewTitleFontPx={
              modeling[MODELING_SLOT_KEYS.MECHANICAL].mobilePreviewTitleFontPx
            }
            mobilePreviewBodyFontPx={
              modeling[MODELING_SLOT_KEYS.MECHANICAL].mobilePreviewBodyFontPx
            }
          />
          <ModelingBlockHeritage
            imageUrlDesktop={modeling[MODELING_SLOT_KEYS.HERITAGE].desktop}
            imageUrlMobile={modeling[MODELING_SLOT_KEYS.HERITAGE].mobile}
            imageUrlTablet={modeling[MODELING_SLOT_KEYS.HERITAGE].tablet}
            titleDesktop={modeling[MODELING_SLOT_KEYS.HERITAGE].titleDesktop}
            titleMobile={modeling[MODELING_SLOT_KEYS.HERITAGE].titleMobile}
            titleTablet={modeling[MODELING_SLOT_KEYS.HERITAGE].titleTablet}
            titleDesktopOffsetY={modeling[MODELING_SLOT_KEYS.HERITAGE].titleDesktopOffsetY}
            titleDesktopOffsetX={modeling[MODELING_SLOT_KEYS.HERITAGE].titleDesktopOffsetX}
            titleMobileOffsetY={modeling[MODELING_SLOT_KEYS.HERITAGE].titleMobileOffsetY}
            titleMobileOffsetX={modeling[MODELING_SLOT_KEYS.HERITAGE].titleMobileOffsetX}
            titleTabletOffsetY={modeling[MODELING_SLOT_KEYS.HERITAGE].titleTabletOffsetY}
            titleTabletOffsetX={modeling[MODELING_SLOT_KEYS.HERITAGE].titleTabletOffsetX}
            descriptionLinesDesktop={toCopyLines(
              modeling[MODELING_SLOT_KEYS.HERITAGE].bodyDesktop,
            )}
            descriptionLinesMobile={toCopyLines(
              modeling[MODELING_SLOT_KEYS.HERITAGE].bodyMobile,
            )}
            descriptionLinesTablet={toCopyLines(
              modeling[MODELING_SLOT_KEYS.HERITAGE].bodyTablet,
            )}
            bodyDesktopOffsetY={modeling[MODELING_SLOT_KEYS.HERITAGE].bodyDesktopOffsetY}
            bodyDesktopOffsetX={modeling[MODELING_SLOT_KEYS.HERITAGE].bodyDesktopOffsetX}
            bodyMobileOffsetY={modeling[MODELING_SLOT_KEYS.HERITAGE].bodyMobileOffsetY}
            bodyMobileOffsetX={modeling[MODELING_SLOT_KEYS.HERITAGE].bodyMobileOffsetX}
            bodyTabletOffsetY={modeling[MODELING_SLOT_KEYS.HERITAGE].bodyTabletOffsetY}
            bodyTabletOffsetX={modeling[MODELING_SLOT_KEYS.HERITAGE].bodyTabletOffsetX}
            mobilePreviewTitleFontPx={
              modeling[MODELING_SLOT_KEYS.HERITAGE].mobilePreviewTitleFontPx
            }
            mobilePreviewBodyFontPx={
              modeling[MODELING_SLOT_KEYS.HERITAGE].mobilePreviewBodyFontPx
            }
          />
          <ModelingBlockHighJewelry
            imageUrlDesktop={modeling[MODELING_SLOT_KEYS.HIGH_JEWELRY].desktop}
            imageUrlMobile={modeling[MODELING_SLOT_KEYS.HIGH_JEWELRY].mobile}
            imageUrlTablet={modeling[MODELING_SLOT_KEYS.HIGH_JEWELRY].tablet}
            titleDesktop={modeling[MODELING_SLOT_KEYS.HIGH_JEWELRY].titleDesktop}
            titleMobile={modeling[MODELING_SLOT_KEYS.HIGH_JEWELRY].titleMobile}
            titleTablet={modeling[MODELING_SLOT_KEYS.HIGH_JEWELRY].titleTablet}
            titleDesktopOffsetY={modeling[MODELING_SLOT_KEYS.HIGH_JEWELRY].titleDesktopOffsetY}
            titleDesktopOffsetX={modeling[MODELING_SLOT_KEYS.HIGH_JEWELRY].titleDesktopOffsetX}
            titleMobileOffsetY={modeling[MODELING_SLOT_KEYS.HIGH_JEWELRY].titleMobileOffsetY}
            titleMobileOffsetX={modeling[MODELING_SLOT_KEYS.HIGH_JEWELRY].titleMobileOffsetX}
            titleTabletOffsetY={modeling[MODELING_SLOT_KEYS.HIGH_JEWELRY].titleTabletOffsetY}
            titleTabletOffsetX={modeling[MODELING_SLOT_KEYS.HIGH_JEWELRY].titleTabletOffsetX}
            descriptionLinesDesktop={toCopyLines(
              modeling[MODELING_SLOT_KEYS.HIGH_JEWELRY].bodyDesktop,
            )}
            descriptionLinesMobile={toCopyLines(
              modeling[MODELING_SLOT_KEYS.HIGH_JEWELRY].bodyMobile,
            )}
            descriptionLinesTablet={toCopyLines(
              modeling[MODELING_SLOT_KEYS.HIGH_JEWELRY].bodyTablet,
            )}
            bodyDesktopOffsetY={modeling[MODELING_SLOT_KEYS.HIGH_JEWELRY].bodyDesktopOffsetY}
            bodyDesktopOffsetX={modeling[MODELING_SLOT_KEYS.HIGH_JEWELRY].bodyDesktopOffsetX}
            bodyMobileOffsetY={modeling[MODELING_SLOT_KEYS.HIGH_JEWELRY].bodyMobileOffsetY}
            bodyMobileOffsetX={modeling[MODELING_SLOT_KEYS.HIGH_JEWELRY].bodyMobileOffsetX}
            bodyTabletOffsetY={modeling[MODELING_SLOT_KEYS.HIGH_JEWELRY].bodyTabletOffsetY}
            bodyTabletOffsetX={modeling[MODELING_SLOT_KEYS.HIGH_JEWELRY].bodyTabletOffsetX}
            desktopLine1Emphasis={
              modeling[MODELING_SLOT_KEYS.HIGH_JEWELRY].desktopLine1Emphasis
            }
            tabletLine1Emphasis={
              modeling[MODELING_SLOT_KEYS.HIGH_JEWELRY].tabletLine1Emphasis
            }
            mobilePreviewTitleFontPx={
              modeling[MODELING_SLOT_KEYS.HIGH_JEWELRY].mobilePreviewTitleFontPx
            }
            mobilePreviewBodyFontPx={
              modeling[MODELING_SLOT_KEYS.HIGH_JEWELRY].mobilePreviewBodyFontPx
            }
          />
          </div>
        </div>
      </div>
    </section>
  );
}
